#!/usr/bin/env bash
# installs nginx
apt-get -y update
apt-get -y upgrade
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
sed -i "/server_name _;/ a\\\trewrite ^/redirect_me https://github.com/andylopezr permanent;" /etc/nginx/sites-available/default
sed -i "/server_name _;/ a\\\tadd_header X-Served-By \"\$HOSTNAME\";" /etc/nginx/sites-available/default
sed -i "/redirect_me/ a\\\terror_page 404 /404.html;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/404.html
service nginx restart
