#!/usr/bin/env bash
# Installs and setups HAproxy
setup="\
frontend load_balancer
    bind *:80
    mode http
    default_backend web_server

backend web_server
    balance roundrobin
    server 2229-web-01 35.190.196.147:80 check
    server 2229-web-02 34.75.12.144:80 check
"
apt-get -y update
apt-get install haproxy=1.6.\*
echo "$setup" >> /etc/haproxy/haproxy.cfg
service haproxy restart
