#!/usr/bin/env bash
# Installs and setups HAproxy
requirements="\
frontend load_balancer
    bind *:80
    mode http
    default_backend web_servers

backend web_servers
    balance roundrobin
    server andy-01 35.190.196.147:80
    server andy-02 34.75.12.144:80
"
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get -y install haproxy=2.0.\*
echo "$requirements" >> /etc/haproxy/haproxy.cfg
service haproxy start
