#!/usr/bin/env bash
#script that displays Holberton School 10 times
i=1
while [ $i -le 9 ]
do
    echo "Holberton School"
    (( i++ ))
    if [ $i == 4 ]
    then
	echo "bad luck"
    elif [ $i == 8 ]
    then
	echo "good luck"
    fi
done
